// Central icon module — wraps lucide-react so every screen uses one consistent
// icon set with shared default sizing/stroke. No emoji anywhere in the product.
import {
  LayoutDashboard, Search, Briefcase, FileText, User, Bell, Sparkles,
  Settings, LogOut, Mail, Phone, MapPin, Globe, Link, GraduationCap,
  Building2, Calendar, Clock, Check, CheckCheck, X, ChevronRight, ChevronLeft,
  ChevronDown, ArrowRight, ArrowUpRight, Star, Bookmark, BookmarkCheck,
  Filter, SlidersHorizontal, Plus, Pencil, Trash2, Download, Upload,
  Send, Video, CalendarPlus, Bell as BellIcon, Lightbulb, Gift, TrendingUp,
  Users, Languages, Wallet, Award, Target, Zap, ShieldCheck, MessageSquare,
  Eye, RotateCcw, AlertCircle, CheckCircle2, Circle, Menu, Lock,
  Network, Cpu, Layers, BadgeCheck, Banknote, Timer, FileCheck, Loader2,
  Building, Workflow, BarChart3, FolderOpen, ClipboardList, Headphones,
} from 'lucide-react';

const map = {
  dashboard: LayoutDashboard,
  search: Search,
  briefcase: Briefcase,
  file: FileText,
  fileCheck: FileCheck,
  user: User,
  users: Users,
  bell: Bell,
  sparkles: Sparkles,
  settings: Settings,
  logout: LogOut,
  mail: Mail,
  phone: Phone,
  location: MapPin,
  globe: Globe,
  linkedin: Link,
  education: GraduationCap,
  company: Building2,
  building: Building,
  calendar: Calendar,
  calendarPlus: CalendarPlus,
  clock: Clock,
  timer: Timer,
  check: Check,
  checkAll: CheckCheck,
  checkCircle: CheckCircle2,
  circle: Circle,
  close: X,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  chevronDown: ChevronDown,
  arrowRight: ArrowRight,
  arrowUpRight: ArrowUpRight,
  star: Star,
  bookmark: Bookmark,
  bookmarkCheck: BookmarkCheck,
  filter: Filter,
  filters: SlidersHorizontal,
  plus: Plus,
  edit: Pencil,
  trash: Trash2,
  download: Download,
  upload: Upload,
  send: Send,
  video: Video,
  lightbulb: Lightbulb,
  gift: Gift,
  trending: TrendingUp,
  languages: Languages,
  wallet: Wallet,
  banknote: Banknote,
  award: Award,
  target: Target,
  zap: Zap,
  shield: ShieldCheck,
  message: MessageSquare,
  eye: Eye,
  reset: RotateCcw,
  alert: AlertCircle,
  menu: Menu,
  lock: Lock,
  network: Network,
  cpu: Cpu,
  layers: Layers,
  badge: BadgeCheck,
  workflow: Workflow,
  chart: BarChart3,
  folder: FolderOpen,
  clipboard: ClipboardList,
  headphones: Headphones,
  spinner: Loader2,
};

export default function Icon({ name, size = 18, strokeWidth = 2, className, style, color }) {
  const Cmp = map[name];
  if (!Cmp) return null;
  return <Cmp size={size} strokeWidth={strokeWidth} className={className} style={style} color={color} />;
}
