import React from "react";

const TONE = {
  default: "#2563EB",
  success: "#10B981",
  warning: "#F59E0B",
  danger: "#EF4444",
};

export function EmailDataSection({ items = [] }) {
  const visible = items.filter((item) => item?.value);
  if (!visible.length) return null;

  return (
    <table role="presentation" width="100%" cellSpacing="0" cellPadding="0" style={{ margin: "20px 0", border: "1px solid #E2E8F0", borderRadius: 14, padding: "4px 16px", background: "#fff" }}>
      <tbody>
        {visible.map((item) => (
          <tr key={item.label}>
            <td style={{ padding: "12px 0", color: "#64748B", fontSize: 13, borderBottom: "1px solid #EEF2F7" }}>{item.label}</td>
            <td align="right" style={{ padding: "12px 0", color: "#0F172A", fontSize: 13, fontWeight: 800, borderBottom: "1px solid #EEF2F7" }}>{item.value}</td>
          </tr>
        ))}
      </tbody>
    </table>
  );
}

export function EmailIllustration({ type = "announcement", tone = "default" }) {
  const accent = TONE[tone] || TONE.default;
  const labels = {
    office: ["TF", "Office Building"],
    person: ["HI", "Candidate Welcome"],
    billing: ["$", "Credit Card + Success Badge"],
    warning: ["!", "Renewal Notice"],
    reminder: ["!", "Smart Reminder"],
    trophy: ["WIN", "Achievement Update"],
    gift: ["BOX", "Offer Package"],
    candidate: ["CV", "Candidate Profile Card"],
    calendar: ["31", "Calendar"],
    success: ["OK", "Success Milestone"],
    score: ["%", "Evaluation Score"],
    contract: ["DOC", "Signed Contract"],
    team: ["HR", "Team Celebration"],
    profile: ["ID", "Profile Progress"],
    learning: ["EDU", "Learning Dashboard"],
    review: ["OKR", "Performance Review"],
    announcement: ["NEW", "Company Announcement"],
    danger: ["!", "Incident Alert"],
    security: ["SEC", "Security Center"],
    ai: ["AI", "AI Processing"],
    analytics: ["BI", "Executive Analytics"],
    revenue: ["$", "Revenue Report"],
  };
  const [icon, label] = labels[type] || labels.announcement;

  return (
    <table role="presentation" width="100%" cellSpacing="0" cellPadding="0" style={{ margin: "22px 0 4px" }}>
      <tbody>
        <tr>
          <td style={{ background: "#F8FAFC", border: "1px solid #E2E8F0", borderRadius: 16, padding: 18 }}>
            <table role="presentation" width="100%" cellSpacing="0" cellPadding="0">
              <tbody>
                <tr>
                  <td width="78">
                    <div style={{ width: 64, height: 64, borderRadius: 18, background: `linear-gradient(135deg,${accent},#4F46E5)`, color: "#fff", fontSize: 17, fontWeight: 900, lineHeight: "64px", textAlign: "center" }}>{icon}</div>
                  </td>
                  <td>
                    <div style={{ fontSize: 13, fontWeight: 800, color: accent, textTransform: "uppercase", letterSpacing: ".08em" }}>{label}</div>
                    <div style={{ fontSize: 14, lineHeight: 1.6, color: "#475569", marginTop: 4 }}>Premium enterprise notification generated by TalentFlow.</div>
                  </td>
                </tr>
              </tbody>
            </table>
          </td>
        </tr>
      </tbody>
    </table>
  );
}

export function EmailProgress({ value = 64 }) {
  const progress = Math.max(0, Math.min(100, parseInt(String(value).replace("%", ""), 10) || 64));
  return (
    <div style={{ margin: "20px 0 4px" }}>
      <table role="presentation" width="100%" cellSpacing="0" cellPadding="0">
        <tbody>
          <tr>
            <td style={{ fontSize: 13, fontWeight: 800, color: "#0F172A" }}>Profile completion</td>
            <td align="right" style={{ fontSize: 13, fontWeight: 800, color: "#2563EB" }}>{progress}%</td>
          </tr>
        </tbody>
      </table>
      <div style={{ height: 10, background: "#E2E8F0", borderRadius: 999, overflow: "hidden", marginTop: 10 }}>
        <div style={{ height: 10, width: `${progress}%`, background: "linear-gradient(135deg,#2563EB,#4F46E5)", borderRadius: 999 }} />
      </div>
    </div>
  );
}

export default function EmailLayout({ title, preheader, badge, children, ctaLabel, ctaUrl, tone = "default" }) {
  const accent = TONE[tone] || TONE.default;
  return (
    <div style={{ background: "#EEF2F7", padding: 28, fontFamily: "Segoe UI, Roboto, Helvetica, Arial, sans-serif" }}>
      <span style={{ display: "none" }}>{preheader}</span>
      <div style={{ maxWidth: 650, margin: "0 auto" }}>
        <div style={{ background: `linear-gradient(135deg,${accent},#4F46E5)`, padding: 32, borderRadius: "18px 18px 0 0", color: "#fff" }}>
          <table role="presentation" width="100%" cellSpacing="0" cellPadding="0">
            <tbody>
              <tr>
                <td>
                  <div style={{ fontSize: 23, fontWeight: 900 }}>TalentFlow</div>
                  <div style={{ fontSize: 13, color: "#DBEAFE", marginTop: 4 }}>AI-Powered Hiring Platform</div>
                </td>
                <td align="right">
                  <div style={{ display: "inline-block", border: "1px solid rgba(255,255,255,.42)", borderRadius: 12, padding: "8px 10px", fontSize: 12, fontWeight: 800 }}>Enterprise</div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
        <div style={{ background: "#fff", padding: 32, border: "1px solid #E2E8F0", borderTop: 0, borderRadius: "0 0 18px 18px", boxShadow: "0 18px 45px rgba(15,23,42,0.08)" }}>
          {badge && <div style={{ display: "inline-block", background: "#EFF6FF", color: accent, border: "1px solid #BFDBFE", borderRadius: 999, padding: "6px 12px", fontSize: 12, fontWeight: 800, marginBottom: 14 }}>{badge}</div>}
          <h1 style={{ margin: "0 0 14px", fontSize: 24, color: "#0F172A" }}>{title}</h1>
          <div style={{ fontSize: 15, lineHeight: 1.75, color: "#334155" }}>{children}</div>
          {ctaLabel && ctaUrl && (
            <div style={{ textAlign: "center", marginTop: 24 }}>
              <a href={ctaUrl} style={{ display: "inline-block", background: `linear-gradient(135deg,${accent},#4F46E5)`, color: "#fff", textDecoration: "none", fontWeight: 800, padding: "14px 28px", borderRadius: 10 }}>{ctaLabel}</a>
            </div>
          )}
        </div>
        <div style={{ textAlign: "center", color: "#64748B", fontSize: 12, lineHeight: 1.7, padding: 20 }}>
          <strong style={{ color: "#0F172A" }}>TalentFlow</strong><br />
          Support: support@talentflow.ai<br />
          Privacy Policy | Terms of Service
        </div>
      </div>
    </div>
  );
}
